#!/bin/sh

  uci set firewall.@zone[1].network='wan wan6 tethering rakitan'
  uci set firewall.@defaults[0].forward='ACCEPT'
  uci set firewall.@zone[1].input='ACCEPT'
  uci set firewall.@zone[1].forward='ACCEPT'
  uci commit firewall

  uci del network.wan6
  uci set network.tethering=interface
  uci set network.tethering.ifname=usb0
  uci set network.tethering.proto=dhcp
  uci set network.rakitan=interface
  uci set network.rakitan.ifname=eth1
  uci set network.rakitan.proto=none
  uci set network.rakitan.force_link=1
  uci add_list network.lan.dns='8.8.8.8'
  uci add_list network.lan.dns='8.8.4.4'
  uci commit network

  uci set system.@system[0]=system 
  uci set system.@system[0].hostname=kzeroo-OpenWrt
  uci set system.@system[0].zonename=Asia/Jakarta
  uci set system.@system[0].timezone=WIB-7
  uci commit system

  uci set dhcp.domain=domain
  uci set dhcp.domain.ip=192.168.1.1
  uci set dhcp.domain.name=kzeroo-OpenWrt
  uci commit dhcp

exit 0
